version: '3.7'
name: 'yii-roadrunner'
services:

  roadrunner:
    container_name: just_roadrunner
    build:
      context: ./docker/roadrunner
    ports:
      - "8080:8080"
    environment:
      RR_VERSION: 2023.1.0
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CONFIG: "client_host=host.docker.internal log_level=0 log=/tmp/xdebug.log"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/roadrunner/config/.rr.yaml:/var/www/.rr.yaml:ro
    command: [ "/usr/bin/rr", "serve", "-d", "-c", ".rr.yaml" ]
    networks:
      - backend

  roadrunner_yii:
    container_name: yii_roadrunner
    build:
      context: ./docker/roadrunner
    ports:
      - "8082:8080"
    environment:
      RR_VERSION: 2023.1.0
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CONFIG: "client_host=host.docker.internal log_level=0 log=/tmp/xdebug.log"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/roadrunner/config/.rr_yii.yaml:/var/www/.rr_yii.yaml:ro
    command: [ "/usr/bin/rr", "serve", "-d", "-c", ".rr_yii.yaml" ]
    networks:
      - backend

  nginx:
    container_name: just_nginx
    image: nginx:latest
    environment:
      NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE: "0"
    ports:
      - "8081:8080"
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/include:/etc/nginx/include
      - ./logs:/var/www/logs
      - ./logs/nginx:/var/www/logs/nginx
    links:
      - php
    networks:
      - backend

  php:
    container_name: test_php
    build: ./docker/php
    volumes:
      - .:/var/www
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend

# Networks Setup
networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/28
