version: '3.7'
name: 'yii-roadrunner'
services:

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CONFIG: "client_host=host.docker.internal log_level=0 log=/tmp/xdebug.log"
    command: ["composer", "install"]
    networks:
      - backend

  roadrunner:
    build:
      context: ./docker/roadrunner
    ports:
      - 8080:8080
    environment:
      RR_VERSION: 2023.1.0
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/roadrunner/config/.rr.yaml:/var/www/rr.yaml:ro
    command: ["/usr/bin/rr", "serve", "-d", "-c", "rr.yaml"]
    networks:
      - backend

# Networks Setup
networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/28
