version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001
server:
  command: "php worker.php"
  env:
    - XDEBUG_SESSION: '0'
http:
  address: :8080
  pool:
    num_workers: 1
    debug: false

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      dirs: [ "/app" ]
